filters:
  - label: "👷🏻‍♂️ status: awaiting triage"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]
    
  - label: "🛠 Feature"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]

  
  - label: "👷🏻‍♂️ status: awaiting triage"
    regexs:
      - /docs/i
    events: [pull_request]
    targets: [title]
  - label: "📄 aspect: docs"
    regexs:
      - /docs/i
    events: [pull_request]
    targets: [title]

  
  - label: "👷🏻‍♂️ status: awaiting triage"
    regexs:
      - /fix/i
    events: [pull_request]
    targets: [title]
  - label: "🐞 Bug"
    regexs:
      - /fix/i
    events: [pull_request]
    targets: [title]
