filters:
  - label: "👷🏻‍♂️ status: awaiting triage"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]
    
  - label: "💡 feature"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]
    
  - label: "hacktoberfest-accepted"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]

  
  - label: "👷🏻‍♂️ status: awaiting triage"
    regexs:
      - /docs/i
    events: [pull_request]
    targets: [title]

  - label: "📚 docs"
    regexs:
      - /docs/i
    events: [pull_request]
    targets: [title]

  - label: "hacktoberfest-accepted"
    regexs:
      - /docs/i
    events: [pull_request]
    targets: [title]


  
  - label: "👷🏻‍♂️ status: awaiting triage"
    regexs:
      - /fix/i
    events: [pull_request]
    targets: [title]

  - label: "🐞 bug"
    regexs:
      - /fix/i
    events: [pull_request]
    targets: [title]

  - label: "hacktoberfest-accepted"
    regexs:
      - /fix/i
    events: [pull_request]
    targets: [title]
