name: 📢 Invitation to the MilanCommunity Organization

description: I would like to be a part of the Milan community.

title: "Please invite me to the GitHub Community Organization"

labels: [invite me to the organisation]

body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your Full name here
    validations:
      required: true

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist ✅"
      options:
        - label: "I have followed the [organisation](https://github.com/MilanCommunity)."
          required: true

        - label: "I will abide by all the [global rules](https://github.com/MilanCommunity/.github/blob/main/CODE_OF_CONDUCT.md) stated here."
          required: true

        - label: "NOTE: Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. Do this by finding your name in the [GitHub organisation list](https://github.com/orgs/MilanCommunity/people) and change the dropdown to public."
          required: true

          