name: Add Label to PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add label to PR
        env:
          PAT_TOKEN: ${{ secrets.ADDLABELPAT }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/IAmTamal/Milan/issues/${{ github.event.pull_request.number }}/labels \
            -d '{"labels":["🧿 status: awaiting triage"]}'
