name: PR Triage Labeler

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Run PR Triage Labeler
        uses: hoho4190/issue-pr-labeler@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file-name: labeler-config.yml
