name: Add triage label to new PRs

on:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  add-triage-label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "👷🏻‍♂️ status: awaiting triage"
