name: Add Label to PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add label to PR
        env:
          PAT_TOKEN: ${{ secrets.ADDLABELPAT }}
        run: |
          # Get the PR title
          PR_TITLE=$(echo "${{ github.event.pull_request.title }}")

          # Set the labels based on PR title
          if [[ $PR_TITLE == fix*:* ]]; then
            LABELS=("🧿 status: awaiting triage" "🛠 goal: fix")
          elif [[ $PR_TITLE == feat*:* ]]; then
            LABELS=("🧿 status: awaiting triage" "⭐ goal: addition")
          elif [[ $PR_TITLE == docs*:* ]]; then
            LABELS=("🧿 status: awaiting triage" "📄 aspect: docs")
          elif [[ $PR_TITLE == build*:* ]]; then
            LABELS=("🧿 status: awaiting triage" "🛠 goal: fix")
          else
            echo "No label matched the PR title"
            exit 0
          fi

          # Add labels to the pull request using GitHub API
          for label in "${LABELS[@]}"; do
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.ADDLABELPAT }}"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/IAmTamal/Milan/issues/${{ github.event.pull_request.number }}/labels" \
              -d "{\"labels\": [\"$label\"]}"
          done
