name: Cypress Tests with Install Job and UI Chrome Job x 5

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Cypress Tests - Chrome"
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          install: true
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/e2e/milanTest.spec.js
