name: E2E on Chrome

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # use docker container to run tests
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Cypress Tests - Chrome"
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          install: true # Install project dependencies
          build: npm run build # create production build fro testing
          start: npm run start # start development server on docker container
          wait-on: "http://localhost:3000" # wait on the projec to start before running tests
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/e2e/*
