name: E2E on Chrome

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
  timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Get npm cache
      - uses: actions/checkout@v2
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm cache dir)"

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies 
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Prepare UI step
        run: npm run build #Install npm dependencies and build the project


      - name: run tests # Run the Cypress tests within our GitHub repository within Electron.
        uses: cypress-io/github-action@v2
        env:
          CI: true
        with:
          install: false
          browser: chrome
          start: npm start #Start the project web server
          wait-on: "http://localhost:3000"
          record: true
          working-directory: cypress/e2e
          # spec: cypress/e2e/milanTest.spec.js
