# name: CI/CD

# on:
#   push:
#     branches:
#       - main

#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Vercel action
#         uses: actions/checkout@v2.3.1
#         # with:
#         #   repository: vercel/actions/cli
#         #   ref: master

#       - name: Install dependencies
#         run: npm install --force

#       - name: Run tests
#         id: run_tests
#         uses: cypress-io/github-action@v3
#         with:
#           record: true

#       - name: Deploy to Vercel
#         if:
#           steps.run_tests.outputs.total_passed ==
#           steps.run_tests.outputs.total_testsdocker pull cypress/browsers:node18.12.0-chrome107
#         uses: vercel/actions/cli@v3
#         with:
#           args: deploy --prod
#         env:
#           NOW_TOKEN: ${{ secrets.NOW_TOKEN }}

name: E2E Tests on Chrome

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # use docker container to run tests
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          HUSKY: 0

      - name: "Cypress Tests - Chrome"
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          install: true # Install project dependencies
          build: npm run build # Create production build for testing
          start: npm run dev # Start development server on docker container
          wait-on: "http://localhost:3000" # wait on the project to start before running tests
          wait-on-timeout: 120 # amount of time to wait on server to start
          browser: chrome # Specify browser to run tests on
          spec: cypress/e2e/* # Specify the test files you'd like to run
        env:
          # temporary fix for eslint warnings being treated as errors.
          # This works for "react": "^17.0.2" and "react-scripts": "^5.0.1". Upgrading any of these packages
          # means that you will have to change this to CI=false
          CI: "false"

  deploy:
    needs: cypress-run
    if: success() # only run this job if the previous job was successful
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: vercel/actions/cli@v3
        with:
          args: deploy --prod
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
