name: CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Vercel action
        uses: actions/checkout@v2.3.1
        # with:
        #   repository: vercel/actions/cli
        #   ref: master

      - name: Install dependencies
        run: npm install --force

      - name: Run tests
        id: run_tests
        uses: cypress-io/github-action@v3
        with:
          record: true

      - name: Deploy to Vercel
        if:
          steps.run_tests.outputs.total_passed ==
          steps.run_tests.outputs.total_tests
        uses: vercel/actions/cli@v3
        with:
          args: deploy --prod
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
